import fs from 'fs';

const definitions = [
    { schema: 'sadova1', name: 'v_effective_stocks', def: "SELECT s.storage_id,\n    st.storage_name,\n    s.ingredient_id,\n    s.ingredient_name,\n    s.storage_ingredient_left AS physical_stock,\n    COALESCE(pending.pending_qty, (0)::bigint) AS virtual_stock,\n    (s.storage_ingredient_left + (COALESCE(pending.pending_qty, (0)::bigint))::numeric) AS effective_stock,\n    s.ingredient_unit\n   FROM ((sadova1.stocks_now s\n     JOIN categories.storages st ON ((st.storage_id = s.storage_id)))\n     LEFT JOIN ( SELECT dr.spot_name,\n            dr.product_name,\n            sum(dr.quantity_to_ship) AS pending_qty\n           FROM sadova1.distribution_results dr\n          WHERE ((dr.delivery_status = 'pending'::text) AND (dr.business_date = CURRENT_DATE))\n          GROUP BY dr.spot_name, dr.product_name) pending ON (((pending.spot_name = st.storage_name) AND (pending.product_name = s.ingredient_name))))\n  WHERE (s.ingredient_id IN ( SELECT production_catalog.product_id\n           FROM sadova1.production_catalog\n          WHERE (production_catalog.is_active = true)));" },
    { schema: 'sadova1', name: 'v_sadova_stats', def: "SELECT db.\"код_продукту\" AS product_id,\n    db.\"назва_продукту\" AS product_name,\n    db.category_name,\n    db.\"код_магазину\" AS storage_id,\n    db.\"назва_магазину\" AS spot_name,\n    db.current_stock AS stock_now,\n    db.avg_sales_day,\n    db.min_stock,\n    GREATEST((0)::numeric, (db.min_stock - db.current_stock)) AS deficit\n   FROM sadova1.distribution_base db\n  WHERE ((db.\"код_продукту\" IN ( SELECT production_catalog.product_id\n           FROM sadova1.production_catalog\n          WHERE (production_catalog.is_active = true))) AND (db.\"код_магазину\" IN ( SELECT distribution_shops.spot_id\n           FROM sadova1.distribution_shops\n          WHERE (distribution_shops.is_active = true))));" },
    { schema: 'sadova1', name: 'v_morning_leftovers', def: "SELECT l.snapshot_date,\n    l.storage_id,\n    l.ingredient_id,\n    l.ingredient_name,\n    l.ingredient_left,\n    l.storage_ingredient_left,\n    l.limit_value,\n    l.ingredient_unit,\n    l.ingredients_type,\n    l.storage_ingredient_sum,\n    l.storage_ingredient_sum_netto,\n    l.prime_cost,\n    l.prime_cost_netto,\n    l.hidden,\n    l.loaded_at,\n    l.api_response_raw\n   FROM (leftovers.daily_snapshots l\n     JOIN sadova1.distribution_shops ds ON ((l.storage_id = ds.storage_id)))\n  WHERE (ds.is_active = true);" },
    { schema: 'sadova1', name: 'v_production_logic', def: "SELECT mi.product_id,\n    max(mi.product_name) AS product_name,\n    (round(sum(mi.quantity)))::integer AS baked_qty\n   FROM (sadova1.manufacture_items mi\n     JOIN sadova1.manufactures m ON ((m.manufacture_id = mi.manufacture_id)))\n  WHERE ((m.manufacture_date >= ((CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Kiev'::text))::date) AND (mi.is_deleted IS NOT TRUE) AND (m.storage_id = 2))\n  GROUP BY mi.product_id;" },
    { schema: 'sadova1', name: 'v_production_tasks', def: "SELECT dr.product_id,\n    dr.product_name,\n    dr.business_date,\n    pc.category_id,\n    pc.category_name,\n    sum(dr.quantity_to_ship) AS total_demand_kg,\n    pc.portion_size AS portion_weight_kg,\n    pc.unit,\n    ceil(((sum(dr.quantity_to_ship))::numeric / pc.portion_size)) AS portions_needed,\n    (ceil(((sum(dr.quantity_to_ship))::numeric / pc.portion_size)) * pc.portion_size) AS actual_production_kg,\n    pc.is_active AS in_production_catalog\n   FROM (sadova1.distribution_results dr\n     LEFT JOIN sadova1.production_catalog pc ON ((dr.product_id = pc.product_id)))\n  WHERE (dr.business_date = CURRENT_DATE)\n  GROUP BY dr.product_id, dr.product_name, dr.business_date, pc.category_id, pc.category_name, pc.portion_size, pc.unit, pc.is_active\n  ORDER BY pc.category_name, dr.product_name;" },
    { schema: 'public', name: 'v_sadova_results_public', def: "SELECT distribution_results.id,\n    distribution_results.product_name AS \"Название продукта\",\n    distribution_results.spot_name AS \"Магазин\",\n    distribution_results.quantity_to_ship AS \"Количество\",\n    distribution_results.created_at AS \"Время расчета\"\n   FROM sadova1.distribution_results\n  WHERE ((distribution_results.created_at)::date = CURRENT_DATE)\n  ORDER BY distribution_results.product_name, distribution_results.spot_name;" },
    { schema: 'public', name: 'v_sadova_production_tasks', def: "SELECT v_production_tasks.product_id,\n    v_production_tasks.product_name,\n    v_production_tasks.business_date,\n    v_production_tasks.category_id,\n    v_production_tasks.category_name,\n    v_production_tasks.total_demand_kg,\n    v_production_tasks.portion_weight_kg,\n    v_production_tasks.unit,\n    v_production_tasks.portions_needed,\n    v_production_tasks.actual_production_kg,\n    v_production_tasks.in_production_catalog\n   FROM sadova1.v_production_tasks;" }
];

let sql = '';
for (const v of definitions) {
    sql += "CREATE OR REPLACE VIEW " + v.schema + "." + v.name + " AS\n" + v.def + "\n\n";
}
fs.writeFileSync('c:/Users/user/Downloads/operator_v2.2-clone/supabase/migrations/20260403_sadova_views_1_basic.sql', sql);
