-- DASHBOARD DEFICIT TABLE
-- Main analytical table for deficit calculation
-- Based on types/bi.ts: SupabaseDeficitRow

CREATE TABLE IF NOT EXISTS public.dashboard_deficit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "код_магазину" bigint,
    "назва_магазину" text,
    "код_продукту" bigint,
    "назва_продукту" text,
    category_name text,
    current_stock numeric,
    min_stock numeric,
    deficit_kg numeric,
    avg_sales_day numeric,
    deficit_percent numeric,
    priority integer, -- 1=critical, 2=high, 3=reserve
    recommended_kg numeric
);

-- AUDIT LOGS TABLE
-- Security and Action logging
-- Based on lib/logger.ts

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id uuid REFERENCES auth.users(id),
    action text NOT NULL,
    target text,
    metadata jsonb,
    ip_address text,
    user_agent text
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.dashboard_deficit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- POLICIES (Basic Read Access)
CREATE POLICY "Allow read for authenticated users" ON public.dashboard_deficit
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert for service role" ON public.audit_logs
    FOR INSERT TO service_role WITH CHECK (true);

CREATE POLICY "Allow insert for authenticated users" ON public.audit_logs
    FOR INSERT TO authenticated WITH CHECK (true);
